### ISSUE TITLE
The exception handler forgets to remove the model. So it leaks, and will never record that model until a restart.

### ISSUE THREAD

**Issue by zewolf5** [SN4T14/capturebate-node#3]
Fix:
	}).catch(errors.ModelOfflineError, function (e) {

		console.log("[" + getCurrentDateTime() + "], e.explanation);

		var modelIndex = modelsCurrentlyCapturing.indexOf(modelName);
		if(modelIndex !== -1) {
			modelsCurrentlyCapturing.splice(modelIndex, 1);
		}

	});

**Comment by SN4T14** [comment]
Fixed, thanks for reporting this!
