### ISSUE TITLE
How to show logged user in broadcast room while rec started?

### ISSUE THREAD

**Issue by alexqill** [SN4T14/capturebate-node#5]
Hi!, how i can show logged user in chat on broadcat room? I need that he will be displayed in "USER LIST" of broadcast chat viewers.

Thank you!

**Comment by SN4T14** [comment]
Hi, right now this is impossible to do, because capturebate-node doesn't connect to the chat in the rooms, but I may implement this in the future! If you know Node, you're also welcome to write the code yourself and submit a pull request. :smile:

**Comment by alexqill** [comment]
Yeah, i'm trying to do that, beacuse this feature will open the great opportunity for pump views on broadcaster room :)

**Comment by SN4T14** [comment]
Right, I'm never going to add a way to do that unless absolutely necessary for other features, this is an archival tool, not a tool for faking stats.
